"""This module implements abstract class Process"""

from abc import ABC, abstractmethod

from numpy import array

from src.main.time_series import TimeSeries


class Process(ABC):
    """Abstract class Process"""

    @property
    @abstractmethod
    def name(self) -> str:
        """Process name"""
        return "base_process"

    @property
    @abstractmethod
    def lag(self) -> int:
        """Process lag (number of previous elements required to compute next element)"""
        return 0

    @property
    @abstractmethod
    def num_parameters(self) -> int:
        """Process parameters number"""
        return 0

    @abstractmethod
    def generate_parameters(
        self, low_value: float, high_value: float
    ) -> tuple[float, ...]:
        """Generates process parameters"""
        return tuple()

    @abstractmethod
    def generate_init_values(self, low_value: float, high_value: float) -> array:
        """Generates process initial values (values number is equal to lag)"""
        return array([])

    @abstractmethod
    def get_info(
        self, sample: tuple[int, tuple], init_values: tuple[float, ...] = None
    ) -> dict:
        """Returns information about process"""
        return {}

    @abstractmethod
    def generate_time_series(
        self,
        sample: tuple[int, tuple],
        previous_values: array = None,
        border_values: tuple[float, float] = None,
    ) -> tuple[TimeSeries, dict]:
        """Generates time series with process"""
        return TimeSeries(), self.get_info(sample)

    @abstractmethod
    def draw_plot(
        self,
        border_values: tuple[float, float] = None,
        path: str = None,
        time_series_data: tuple[TimeSeries, dict] = None,
    ):
        """Draws plot of time series, generated by process"""
        return
